VN30 = ['BID', 'CTG', 'EIB', 'FPT', 'GAS', 'HDB', 'HPG', 'KDH', 'MBB', 'MSN', 'MWG', 'NVL', 'PLX',
        'PNJ', 'POW', 'REE', 'ROS', 'SAB', 'SBT', 'SSI', 'STB', 'TCB', 'TCH', 'VCB', 'VHM', 'VIC',
        'VJC', 'VNM','VPB', 'VRE']

HNX30 = ['ACB', 'BVS', 'CAP', 'CEO', 'DDG', 'DHT', 'DP3', 'DTD', 'HUT', 'KLF', 'L14', 'LHC', 'MBS',
    'NBC', 'NDN', 'NRC', 'PVB', 'PVC', 'PVI', 'PVS', 'SHB', 'SHS', 'SLS', 'TNG', 'TVC', 'VC3',
         'VCG', 'VCS', 'VGS', 'VMC']

# dung o STB
# HOSE = [ ]
# HNX = []

# HOSE = []
HOSE = ['NKG', 'DHC', 'SRC', 'PTL', 'TDG', 'HQC', 'GTA', 'TMT', 'HDC', 'D2D', 'CCI', 'UIC', 'CSV', 'BTT', 'TN1', 'RDP', 'DTL', 'HHS', 'HU3', 'SGR', 'SAV', 'DIG', 'NT2', 'BMP', 'TCH', 'VID', 'SFG', 'ACC', 'HCM', 'PVT', 'TRA', 'HVN', 'APH', 'VCB', 'PAN', 'GMC', 'NSC', 'HTL', 'DC4', 'PNJ', 'DGW', 'VPG', 'PMG', 'KHP', 'VNG', 'TCR', 'TCD', 'PHC', 'SZC', 'JVC', 'DRH', 'NAF', 'CRC', 'VTB', 'TCO', 'LGL', 'DBC', 'VMD', 'FTS', 'CMG', 'HCD', 'AGG', 'ABS', 'ASG', 'HTI', 'LBM', 'DAT', 'KDC', 'LIX', 'ANV', 'ACB', 'DTT', 'SAM', 'VNS', 'ILB', 'FCN', 'HAS', 'NBB', 'VSC', 'BBC', 'GMD', 'SMC', 'DXV', 'FMC', 'PET', 'LCM', 'DPM', 'DTA', 'TIP', 'LGC', 'TDC', 'TV2', 'QCG', 'APG', 'PDR', 'TLH', 'CDC', 'SVC', 'OGC', 'VIB', 'BIC', 'TPB', 'ASP', 'MWG', 'SMA', 'VPD', 'HDG', 'HAI', 'DBT', 'HAX', 'GSP', 'ITA', 'VPS', 'HDB', 'HSL', 'HVX', 'SBT', 'GAS', 'CTI', 'VDP', 'DGC', 'AGM', 'ST8', 'TDP', 'MDG', 'UDC', 'DSN', 'FCM', 'TTB', 'AGR', 'HMC', 'VHM', 'TBC', 'ELC', 'VRE', 'BTP', 'HAG', 'PME', 'GDT', 'LDG', 'HVH', 'LHG', 'KPF', 'PDN', 'DQC', 'REE', 'ASM', 'BMC', 'DHG', 'PLP', 'FIR', 'FRT', 'TDH', 'BWE', 'TTA', 'SVI', 'TEG', 'GIL', 'VSI', 'SBV', 'ROS', 'VOS', 'TNT', 'DPR', 'CTD', 'SSI', 'PTC', 'NHH', 'DCM', 'GTN', 'PVD', 'SCD', 'HOT', 'EVG', 'PPC', 'IDI', 'TCT', 'VND', 'AST', 'SFC', 'HID', 'SPM', 'SHA', 'YBM', 'VIC', 'KDH', 'SC5', 'SJS', 'PLX', 'NVL', 'HBC', 'DVP', 'PHR', 'DPG', 'EVE', 'VHC', 'DRC', 'BCG', 'BMI', 'TLG', 'SCS', 'THG', 'AAA', 'VNE', 'CTG', 'VJC', 'LCG', 'DAG', 'AMD', 'SHI', 'CCL', 'NTL', 'CLC', 'CSM', 'SAB', 'CNG', 'BCE', 'KMR', 'HII', 'C47', 'MSN', 'SBA', 'LPB', 'RIC', 'OPC', 'COM', 'DRL', 'VCI', 'TMP', 'SII', 'TYA', 'DBD', 'FIT', 'HSG', 'VGC', 'SHP', 'VRC', 'DCL', 'CKG', 'PSH', 'TCB', 'DXG', 'TNI', 'CHP', 'HUB', 'VCF', 'TAC', 'BID', 'CTS', 'THI', 'TTE', 'ADS', 'SJF', 'IMP', 'MHC', 'PIT', 'MCG', 'YEG', 'L10', 'TS4', 'C32', 'STB', 'PGI', 'SGT', 'LEC', 'HAR', 'CII', 'SMB', 'GVR', 'VPB', 'CIG', 'HT1', 'LSS', 'BVH', 'VPH', 'QBS', 'AAM', 'PXT', 'TGG', 'SGN', 'PTB', 'HRC', 'POW', 'PGD', 'NNC', 'TNC', 'DLG', 'S4A', 'VPI', 'NLG', 'FTM', 'HPX', 'SFI', 'PGC', 'TCL', 'ITD', 'SCR', 'TVB', 'KOS', 'HU1', 'TVS', 'CLG', 'CEE', 'HAP', 'LAF', 'TPC', 'IJC', 'HTN', 'NVT', 'TCM', 'PNC', 'BCM', 'FPT', 'VIS', 'VIP', 'RAL', 'PXS', 'PJT', 'TTF', 'TSC', 'VDS', 'TNA', 'HTV', 'TIX', 'GAB', 'DMC', 'CVT', 'MBB', 'EIB', 'CAV', 'GEG', 'PAC', 'CRE', 'LM8', 'HAH', 'FLC', 'STK', 'KBC', 'SKG', 'NCT', 'TDM', 'BHN', 'ACL', 'SZL', 'POM', 'IBC', 'STG', 'HPG', 'CLL', 'DHA', 'ICT', 'HNG', 'ABT', 'TLD', 'TVT', 'VSH', 'APC', 'MSH', 'SVT', 'PXI', 'CMX', 'TMS', 'BFC', 'VTO', 'GEX', 'VAF', 'PC1', 'SRF', 'VNM', 'CTF', 'MCP', 'SJD', 'BSI', 'ITC', 'DHM', 'DAH', 'KSB']
#
HNX = ['MIM', 'CKV', 'GIC', 'KVC', 'BAX', 'PPY', 'X20', 'DZM', 'VHE', 'HAT', 'QTC', 'CSC', 'NDN', 'NET', 'NST', 'KDM', 'VBC', 'SMN', 'SZB', 'VE8', 'HAD', 'KLF', 'PCE', 'VCM', 'NHA', 'PIA', 'BII', 'TJC', 'PVC', 'PCG', 'DXP', 'MBS', 'PRC', 'VCS', 'PVI', 'TTT', 'TIG', 'TMB', 'MCO', 'DAE', 'VC3', 'VE1', 'DP3', 'CTX', 'TDN', 'DAD', 'PSW', 'UNI', 'PJC', 'CVN', 'ITQ', 'V21', 'NDX', 'BKC', 'HUT', 'NTH', 'ONE', 'MBG', 'LHC', 'CTT', 'SIC', 'ADC', 'VIF', 'PVG', 'NTP', 'PHP', 'TVD', 'SSM', 'SED', 'ART', 'RCL', 'VIG', 'KST', 'LUT', 'SD9', 'NRC', 'SLS', 'S55', 'STP', 'WSS', 'VC6', 'PHN', 'IDJ', 'HHC', 'TV4', 'SJ1', 'VC1', 'DC2', 'MAC', 'NBC', 'VMC', 'VTC', 'NSH', 'NVB', 'AAV', 'FID', 'PSI', 'TAR', 'PTI', 'SGH', 'CEO', 'INN', 'CET', 'IDC', 'MST', 'VC9', 'LDP', 'PPP', 'LAS', 'HJS', 'DNM', 'NAG', 'TKU', 'LCS', 'VTJ', 'PVS', 'TV3', 'KKC', 'BVS', 'MPT', 'CMS', 'IVS', 'LM7', 'HDA', 'DHT', 'VE4', 'VSM', 'BCF', 'SDN', 'HMH', 'GMA', 'HCT', 'HHG', 'GLT', 'HLD', 'THD', 'KSQ', 'SDC', 'GKM', 'PTS', 'S74', 'SVN', 'MCF', 'VGS', 'HCC', 'PV2', 'THT', 'SHB', 'PSD', 'TTZ', 'STC', 'TVC', 'VIX', 'SHS', 'PMC', 'PDC', 'VHL', 'TA9', 'VNC', 'CIA', 'TKC', 'TNG', 'CPC', 'NHC', 'V12', 'SHN', 'HBS', 'ACM', 'SJE', 'BCC', 'L14', 'VNT', 'SGD', 'MHL', 'S99', 'L43', 'DDG', 'KTT', 'L61', 'ATS', 'SCI', 'SEB', 'SFN', 'PLC', 'DST', 'TTC', 'NBP', 'API', 'LIG', 'SD4', 'MVB', 'PIC', 'VMS', 'IDV', 'BTS', 'SRA', 'KSD', 'NGC', 'SDG', 'VXB', 'HVT', 'VCC', 'PGS', 'WCS', 'SAF', 'HKT', 'HOM', 'QST', 'SPI', 'TMX', 'SDT', 'EVS', 'CLH', 'PSC', 'PGN', 'VKC', 'C92', 'VTV', 'VIT', 'BNA', 'CDN', 'POT', 'D11', 'TTH', 'TXM', 'DNC', 'C69', 'PVB', 'VCG', 'NBW', 'CTP', 'PPS', 'APS', 'NAP', 'TC6', 'SD2', 'CAP', 'AMV', 'THB', 'SD6', 'VC7', 'SD5', 'EID', 'DTD', 'PCT', 'SDA', 'QHD', 'HLC', 'MAS', 'VNR', 'DS3', 'HHP', 'PVL', 'TDT', 'VSA']
# HNX = [ 'SD6', 'VC7', 'SD5', 'EID', 'DTD', 'PCT', 'SDA', 'QHD', 'HLC', 'MAS', 'VNR', 'DS3', 'HHP', 'PVL', 'TDT', 'VSA']

# HNX = ['AAV', 'FID', 'PSI', 'TAR', 'PTI', 'SGH', 'CEO', 'INN', 'CET', 'IDC', 'MST', 'VC9', 'LDP', 'PPP', 'LAS', 'HJS', 'DNM', 'NAG', 'TKU', 'LCS', 'VTJ', 'PVS', 'TV3', 'KKC', 'BVS', 'MPT', 'CMS', 'IVS', 'LM7', 'HDA', 'DHT', 'VE4', 'VSM', 'BCF', 'SDN', 'HMH', 'GMA', 'HCT', 'HHG', 'GLT', 'HLD', 'THD', 'KSQ', 'SDC', 'GKM', 'PTS', 'S74', 'SVN', 'MCF', 'VGS', 'HCC', 'PV2', 'THT', 'SHB', 'PSD', 'TTZ', 'STC', 'TVC', 'VIX', 'SHS', 'PMC', 'PDC', 'VHL', 'TA9', 'VNC', 'CIA', 'TKC', 'TNG', 'CPC', 'NHC', 'V12', 'SHN', 'HBS', 'ACM', 'SJE', 'BCC', 'L14', 'VNT', 'SGD', 'MHL', 'S99', 'L43', 'DDG', 'KTT', 'L61', 'ATS', 'SCI', 'SEB', 'SFN', 'PLC', 'DST', 'TTC', 'NBP', 'API', 'LIG', 'SD4', 'MVB', 'PIC', 'VMS', 'IDV', 'BTS', 'SRA', 'KSD', 'NGC', 'SDG', 'VXB', 'HVT', 'VCC', 'PGS', 'WCS', 'SAF', 'HKT', 'HOM', 'QST', 'SPI', 'TMX', 'SDT', 'EVS', 'CLH', 'PSC', 'PGN', 'VKC', 'C92', 'VTV', 'VIT', 'BNA', 'CDN', 'POT', 'D11', 'TTH', 'TXM', 'DNC', 'C69', 'PVB', 'VCG', 'NBW', 'CTP', 'PPS', 'APS', 'NAP', 'TC6', 'SD2', 'CAP', 'AMV', 'THB', 'SD6', 'VC7', 'SD5', 'EID', 'DTD', 'PCT', 'SDA', 'QHD', 'HLC', 'MAS', 'VNR', 'DS3', 'HHP', 'PVL', 'TDT', 'VSA']
UPCOM = ['MTA', 'DDV', 'SGS', 'CT6', 'NDP', 'LKW', 'NTC', 'PMJ', 'SGP', 'G36', 'IPA', 'PNP', 'TGP', 'BWS', 'C4G', 'NNG', 'ACE', 'ABC', 'QNC', 'PTT', 'IFS', 'SCL', 'CCR', 'NTW', 'SPD', 'DSG', 'PPH', 'MH3', 'ACV', 'CC1', 'PEQ', 'AG1', 'MHP', 'DNH', 'XPH', 'AFX', 'MFS', 'BAB', 'DPH', 'NED', 'QPH', 'DTC', 'SKV', 'XMC', 'PAS', 'BBT', 'EVF', 'SKH', 'ITS', 'C21', 'MGG', 'OIL', 'AGP', 'CKD', 'MCH', 'MIG', 'NS3', 'PVO', 'HPT', 'ISH', 'CQN', 'KSH', 'MRF', 'HDM', 'EIC', 'PTV', 'HIG', 'HFC', 'DNA', 'PFL', 'AAS', 'SWC', 'HTM', 'ATB', 'BHA', 'PMT', 'SZE', 'DNW', 'PND', 'ABI', 'CEN', 'DHD', 'SRT', 'DTK', 'DTV', 'SIP', 'LMC', 'HEM', 'MLS', 'BRR', 'KTL', 'M10', 'HKP', 'BTN', 'BLI', 'DDN', 'SNZ', 'SRB', 'HNI', 'HPP', 'CI5', 'MSR', 'GHC', 'ADG', 'C71', 'DVN', 'HPB', 'DRI', 'DCR', 'ICF', 'TA6', 'CLX', 'HU4', 'HLB', 'SDD', 'GVT', 'ILS', 'SAS', 'FOX', 'FOC', 'SD3', 'QNS', 'TCI', 'BDG', 'STH', 'DVC', 'EMS', 'ICI', 'MC3', 'HNA', 'CSI', 'BMS', 'HUG', 'HD2', 'NUE', 'MML', 'NMK', 'CNC', 'APF', 'RTB', 'HPH', 'HSI', 'PNG', 'ICN', 'GND', 'LTG', 'NCS', 'PRT', 'TID', 'ORS', 'PSL', 'SDK', 'KHA', 'QTP', 'THU', 'LIC', 'SJG', 'BVG', 'HND', 'BSA', 'HEC', 'BSL', 'CCM', 'HMS', 'PDV', 'SAC', 'SSN', 'HHV', 'PGV', 'HTE', 'TCW', 'DSC', 'DBM', 'ADP', 'BOT', 'HPI', 'POS', 'L12', 'SEA', 'CTR', 'NAB', 'HNF', 'DSP', 'SID', 'PSP', 'HDP', 'BUD', 'BSQ', 'EIN', 'MPC', 'BTD', 'NAS', 'DCF', 'IST', 'ND2', 'PSB', 'PVV', 'MTH', 'PXL', 'NHT', 'DTP', 'LLM', 'PVM', 'DC1', 'DAP', 'THP', 'BSR', 'HAN', 'HC3', 'NDC', 'KTC', 'BHP', 'BVB', 'MKP', 'CAT', 'AMS', 'TDS', 'PVP', 'CMT', 'DTB', 'HTG', 'PWA', 'DND', 'CDO', 'BDT', 'DTI', 'PCM', 'SGB', 'PCC', 'ILA', 'BAL', 'SBS', 'KLB', 'BWA', 'MQN', 'SCJ', 'ABR', 'CDP', 'HNE', 'SPV', 'MTG']
# UPCOM = []