# HOSE = ['VIC', 'FPT' ]
# HNX = []
#
fail_stock = ['STG', 'VPI', 'HID', 'VGC', 'BID', 'SIC', 'GEX', 'VDS', 'EVG', 'VNS', 'DXG', 'VPG', 'MCF', 'VNE', 'EMC', 'FCN', 'ST8', 'VID', 'VPB', 'TPC', 'UIC', 'VRC', 'FTM', 'SZB', 'VNL', 'DIG', 'YEG', 'VMD', 'GAB', 'VHM', 'GSP', 'HDG', 'VIS', 'TYA', 'MCG', 'TVS', 'GDT', 'VNT', 'APH', 'VKC', 'HDB', 'AMD', 'EIB', 'DSN', 'FPT', 'FLC', 'GMC', 'PDR', 'TCD', 'VIT', 'ART', 'HAI', 'BVH', 'DTL', 'VCB', 'FID', 'VSC', 'BTP', 'VCI', 'PMG']

HOSE = ['NKG', 'DHC', 'SRC', 'PTL', 'TDG', 'HQC', 'GTA', 'TMT', 'HDC', 'D2D', 'CCI', 'UIC', 'CSV', 'BTT', 'TN1', 'RDP', 'DTL', 'HHS', 'HU3', 'SGR', 'SAV', 'DIG', 'NT2', 'BMP', 'TCH', 'VID', 'SFG', 'ACC', 'HCM', 'PVT', 'TRA', 'HVN', 'APH', 'VCB', 'PAN', 'GMC', 'NSC', 'HTL', 'DC4', 'PNJ', 'DGW', 'VPG', 'PMG', 'KHP', 'VNG', 'TCR', 'TCD', 'PHC', 'SZC', 'JVC', 'DRH', 'NAF', 'CRC', 'VTB', 'TCO', 'LGL', 'DBC', 'VMD', 'FTS', 'CMG', 'HCD', 'AGG', 'ABS', 'ASG', 'HTI', 'LBM', 'DAT', 'KDC', 'LIX', 'ANV', 'ACB', 'DTT', 'SAM', 'VNS', 'ILB', 'FCN', 'HAS', 'NBB', 'VSC', 'BBC', 'GMD', 'SMC', 'DXV', 'FMC', 'PET', 'LCM', 'DPM', 'DTA', 'TIP', 'LGC', 'TDC', 'TV2', 'QCG', 'APG', 'PDR', 'TLH', 'CDC', 'SVC', 'OGC', 'VIB', 'BIC', 'TPB', 'ASP', 'MWG', 'SMA', 'VPD', 'HDG', 'HAI', 'DBT', 'HAX', 'GSP', 'ITA', 'VPS', 'HDB', 'HSL', 'HVX', 'SBT', 'GAS', 'CTI', 'VDP', 'DGC', 'AGM', 'ST8', 'TDP', 'MDG', 'UDC', 'DSN', 'FCM', 'TTB', 'AGR', 'HMC', 'VHM', 'TBC', 'ELC', 'VRE', 'BTP', 'HAG', 'PME', 'GDT', 'LDG', 'HVH', 'LHG', 'KPF', 'PDN', 'DQC', 'REE', 'ASM', 'BMC', 'DHG', 'PLP', 'FIR', 'FRT', 'TDH', 'BWE', 'TTA', 'SVI', 'TEG', 'GIL', 'VSI', 'SBV', 'ROS', 'VOS', 'TNT', 'DPR', 'CTD', 'SSI', 'PTC', 'NHH', 'DCM', 'GTN', 'PVD', 'SCD', 'HOT', 'EVG', 'PPC', 'IDI', 'TCT', 'VND', 'AST', 'SFC', 'HID', 'SPM', 'SHA', 'YBM', 'VIC', 'KDH', 'SC5', 'SJS', 'PLX', 'NVL', 'HBC', 'DVP', 'PHR', 'DPG', 'EVE', 'VHC', 'DRC', 'BCG', 'BMI', 'TLG', 'SCS', 'THG', 'AAA', 'VNE', 'CTG', 'VJC', 'LCG', 'DAG', 'AMD', 'SHI', 'CCL', 'NTL', 'CLC', 'CSM', 'SAB', 'CNG', 'BCE', 'KMR', 'HII', 'C47', 'MSN', 'SBA', 'LPB', 'RIC', 'OPC', 'COM', 'DRL', 'VCI', 'TMP', 'SII', 'TYA', 'DBD', 'FIT', 'HSG', 'VGC', 'SHP', 'VRC', 'DCL', 'CKG', 'PSH', 'TCB', 'DXG', 'TNI', 'CHP', 'HUB', 'VCF', 'TAC', 'BID', 'CTS', 'THI', 'TTE', 'ADS', 'SJF', 'IMP', 'MHC', 'PIT', 'MCG', 'YEG', 'L10', 'TS4', 'C32', 'STB', 'PGI', 'SGT', 'LEC', 'HAR', 'CII', 'SMB', 'GVR', 'VPB', 'CIG', 'HT1', 'LSS', 'BVH', 'VPH', 'QBS', 'AAM', 'PXT', 'TGG', 'SGN', 'PTB', 'HRC', 'POW', 'PGD', 'NNC', 'TNC', 'DLG', 'S4A', 'VPI', 'NLG', 'FTM', 'HPX', 'SFI', 'PGC', 'TCL', 'ITD', 'SCR', 'TVB', 'KOS', 'HU1', 'TVS', 'CLG', 'CEE', 'HAP', 'LAF', 'TPC', 'IJC', 'HTN', 'NVT', 'TCM', 'PNC', 'BCM', 'FPT', 'VIS', 'VIP', 'RAL', 'PXS', 'PJT', 'TTF', 'TSC', 'VDS', 'TNA', 'HTV', 'TIX', 'GAB', 'DMC', 'CVT', 'MBB', 'EIB', 'CAV', 'GEG', 'PAC', 'CRE', 'LM8', 'HAH', 'FLC', 'STK', 'KBC', 'SKG', 'NCT', 'TDM', 'BHN', 'ACL', 'SZL', 'POM', 'IBC', 'STG', 'HPG', 'CLL', 'DHA', 'ICT', 'HNG', 'ABT', 'TLD', 'TVT', 'VSH', 'APC', 'MSH', 'SVT', 'PXI', 'CMX', 'TMS', 'BFC', 'VTO', 'GEX', 'VAF', 'PC1', 'SRF', 'VNM', 'CTF', 'MCP', 'SJD', 'BSI', 'ITC', 'DHM', 'DAH', 'KSB']


HNX = ['MIM', 'CKV', 'GIC', 'KVC', 'BAX', 'PPY', 'X20', 'DZM', 'VHE', 'HAT', 'QTC', 'CSC', 'NDN', 'NET', 'NST', 'KDM', 'VBC', 'SMN', 'SZB', 'VE8', 'HAD', 'KLF', 'PCE', 'VCM', 'NHA', 'PIA', 'BII', 'TJC', 'PVC', 'PCG', 'DXP', 'MBS', 'PRC', 'VCS', 'PVI', 'TTT', 'TIG', 'TMB', 'MCO', 'DAE', 'VC3', 'VE1', 'DP3', 'CTX', 'TDN', 'DAD', 'PSW', 'UNI', 'PJC', 'CVN', 'ITQ', 'V21', 'NDX', 'BKC', 'HUT', 'NTH', 'ONE', 'MBG', 'LHC', 'CTT', 'SIC', 'ADC', 'VIF', 'PVG', 'NTP', 'PHP', 'TVD', 'SSM', 'SED', 'ART', 'RCL', 'VIG', 'KST', 'LUT', 'SD9', 'NRC', 'SLS', 'S55', 'STP', 'WSS', 'VC6', 'PHN', 'IDJ', 'HHC', 'TV4', 'SJ1', 'VC1', 'DC2', 'MAC', 'NBC', 'VMC', 'VTC', 'NSH', 'NVB', 'AAV', 'FID', 'PSI', 'TAR', 'PTI', 'SGH', 'CEO', 'INN', 'CET', 'IDC', 'MST', 'VC9', 'LDP', 'PPP', 'LAS', 'HJS', 'DNM', 'NAG', 'TKU', 'LCS', 'VTJ', 'PVS', 'TV3', 'KKC', 'BVS', 'MPT', 'CMS', 'IVS', 'LM7', 'HDA', 'DHT', 'VE4', 'VSM', 'BCF', 'SDN', 'HMH', 'GMA', 'HCT', 'HHG', 'GLT', 'HLD', 'THD', 'KSQ', 'SDC', 'GKM', 'PTS', 'S74', 'SVN', 'MCF', 'VGS', 'HCC', 'PV2', 'THT', 'SHB', 'PSD', 'TTZ', 'STC', 'TVC', 'VIX', 'SHS', 'PMC', 'PDC', 'VHL', 'TA9', 'VNC', 'CIA', 'TKC', 'TNG', 'CPC', 'NHC', 'V12', 'SHN', 'HBS', 'ACM', 'SJE', 'BCC', 'L14', 'VNT', 'SGD', 'MHL', 'S99', 'L43', 'DDG', 'KTT', 'L61', 'ATS', 'SCI', 'SEB', 'SFN', 'PLC', 'DST', 'TTC', 'NBP', 'API', 'LIG', 'SD4', 'MVB', 'PIC', 'VMS', 'IDV', 'BTS', 'SRA', 'KSD', 'NGC', 'SDG', 'VXB', 'HVT', 'VCC', 'PGS', 'WCS', 'SAF', 'HKT', 'HOM', 'QST', 'SPI', 'TMX', 'SDT', 'EVS', 'CLH', 'PSC', 'PGN', 'VKC', 'C92', 'VTV', 'VIT', 'BNA', 'CDN', 'POT', 'D11', 'TTH', 'TXM', 'DNC', 'C69', 'PVB', 'VCG', 'NBW', 'CTP', 'PPS', 'APS', 'NAP', 'TC6', 'SD2', 'CAP', 'AMV', 'THB', 'SD6', 'VC7', 'SD5', 'EID', 'DTD', 'PCT', 'SDA', 'QHD', 'HLC', 'MAS', 'VNR', 'DS3', 'HHP', 'PVL', 'TDT', 'VSA']


TOTALSTOCK  = ['V12']

STOCK_NOT_CRAWLED = ['SDN', 'HTL', 'FCM', 'TRA', 'LCS', 'MIM', 'ICT', 'IJC', 'VPH', 'CHP', 'CMX', 'LUT', 'LHG', 'GDW', 'BMC', 'EMC', 'VIE', 'KOS', 'ST8', 'COM', 'AAM', 'DNM', 'NVT', 'MCF', 'ACL', 'IMP', 'DXP', 'DRL', 'STB', 'TDP', 'HCC', 'BCG', 'BMP', 'MBB', 'KSB', 'PTD', 'SRA', 'CLH', 'HAI', 'D11', 'TA9', 'TDT', 'SHE', 'TCM', 'DAG', 'GSP', 'LM7', 'VPG', 'DAT', 'EVE', 'HJS', 'EIB', 'TTT', 'VDP', 'NDX', 'DXV', 'HUT', 'TJC', 'CII', 'DBD', 'MSN', 'TVB', 'KVC', 'SJS', 'CTX', 'SHA', 'AME', 'PBP', 'YBM', 'SFI', 'DCM', 'S74', 'NHC', 'TNI', 'VE3', 'TTA', 'OPC', 'BID', 'ATS', 'PGS', 'PXI', 'GMA', 'TKU', 'GEG', 'ACM', 'MBS', 'PSD', 'GEX', 'FIT', 'PIT', 'SLS', 'POM', 'DLG', 'TCB', 'HHG', 'NAF', 'CEO', 'HID', 'FDC', 'DC2', 'DVP', 'ABT', 'CRE', 'FLC', 'HHS', 'NST', 'VC1', 'CCI', 'GLT', 'TDC', 'L62', 'TVC', 'TTH', 'GTA', 'VIP', 'TS4', 'PTB', 'SPM', 'WCS', 'PAN', 'MVB', 'NSC', 'CDC', 'CTI', 'VAF', 'CMG', 'HII', 'GICAAV', 'TNA', 'WSS', 'YEG', 'DPR', 'HOM', 'UIC', 'VSA', 'SGR', 'PPP', 'UDC', 'DHC', 'FID', 'C92', 'BSI', 'TVT', 'GAB', 'DIG', 'KDC', 'SFC', 'STK', 'PHN', 'TLG', 'SHP', 'VJC', 'TXM', 'DBT', 'NGC', 'HAH', 'NTP', 'FCN', 'STG', 'THB', 'EVG', 'VCS', 'SAB', 'FPT', 'CPC', 'TAC', 'INC', 'VNR', 'ITQ', 'NLG', 'PMB', 'HDA', 'LHC', 'PTS', 'BWE', 'KDM', 'PTC', 'IDJ', 'SD5', 'SMT', 'CVT', 'API', 'VHE', 'TDW', 'LAF', 'TMP', 'TCR', 'SZC', 'VC3', 'TPP', 'CMC', 'TST', 'VIX', 'HKT', 'TIX', 'VND', 'PDR', 'VNL', 'POT', 'CSV', 'VTC', 'HLD', 'PGD', 'VIC', 'KKC', 'PCG', 'PPY', 'HDB', 'SGH', 'BTT', 'SJD', 'VCF', 'KHP', 'SZB', 'PET', 'PIA', 'DDG', 'NBC', 'V21', 'VPS', 'HSG', 'APH', 'SJ1', 'PVB', 'MAS', 'VTL', 'BVH', 'SIC', 'GMD', 'MCP', 'BTS', 'TMC', 'SC5', 'BAX', 'VMD', 'MED', 'HU3', 'SVN', 'MCG', 'SHS', 'CLC', 'LDG', 'HDG', 'VID', 'TVS', 'VMC', 'LGC', 'FTS', 'ITC', 'DHM', 'NHH', 'QCG', 'MST', 'ELC', 'TPB', 'ASM', 'BIC', 'DPG', 'DHT', 'SRF', 'PDN', 'CTB', 'AGG', 'PVL', 'VC9', 'SCR', 'APS', 'LM8', 'VCI', 'HAP', 'CIA', 'OCH', 'HPG', 'SD9', 'RIC', 'APG', 'DAE', 'GDT', 'TV3', 'S4A', 'VRC', 'VC6', 'MHC', 'VDS', 'TDH', 'TTB', 'VHC', 'TCH', 'DXG', 'DGW', 'DTL', 'QHD', 'VNE', 'CTP', 'SAV', 'CLL', 'VNS', 'AGR', 'HCM', 'TNG', 'ICG', 'VHM', 'ALT', 'SAF', 'BBC', 'PPC', 'VTV', 'SSI', 'VCG', 'BFC', 'GAS', 'VGC', 'VIS', 'STC', 'VNT', 'PEN', 'VCB', 'THI', 'VPD', 'ART', 'PVD', 'BTP', 'TCD', 'VFG', 'NBW', 'NBB', 'FRT', 'HAS', 'NRC', 'HDC', 'VOS', 'DSN', 'SD2', 'BXH', 'ANV', 'SBT', 'C47', 'PVG', 'DRC', 'CTF', 'DC4', 'CAP', 'FMC', 'SMB', 'PMP', 'MKV', 'HBC', 'DST', 'SDC', 'VNM', 'EVS', 'RCL', 'LCG', 'SVI', 'HNG', 'FTM', 'TC6', 'VPI', 'AST', 'VIT', 'MCO', 'SED', 'VNC', 'JVC', 'GVR', 'HTV', 'HVX', 'VIG', 'SDU', 'BKC', 'DTA', 'TTF', 'HQC', 'PXT', 'TMT', 'NAP', 'TYA', 'NTL', 'BCF', 'VE8', 'EBS', 'HVH', 'VRE', 'AMD', 'VNG', 'VTB', 'VKC', 'KST', 'RDP', 'VPB', 'QST', 'PLP', 'L43', 'HT1', 'PME', 'SGC', 'PHC', 'GIL', 'KSD', 'PMG', 'PNC', 'PDB', 'TPC', 'THT', 'PJC', 'VSC', 'VGP', 'BPC', 'DP3', 'VSH', 'TGG', 'HAT', 'GMC']

if __name__ == "__main__":
    print(list(set(HOSE + HNX + TOTALSTOCK + STOCK_NOT_CRAWLED)))